version: '3'
services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./:/app/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project1
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - mysql-ntw

networks:
  mysql-ntw:
    driver: bridge

volumes:
  mysql-vol: